/**
 * Generate the English edition of the analytical content.
 *
 *   bun run translate:content                      only new/changed strings
 *   bun run translate:content -- --force           re-translate everything
 *   bun run translate:content -- --dry-run         translate, report, write nothing
 *   bun run translate:content -- --model=<id> --concurrency=6
 *
 * Inputs (Chinese, canonical, version controlled):
 *   content/metrics.json    per-metric explainers, sources already expanded
 *   content/insights.json   data insights, sources stored as refs
 *   content/sources.json    the provenance registry
 *
 * Outputs (English, generated, also version controlled so the repo is usable
 * without an API key):
 *   content/metrics.en.json
 *   content/insights.en.json
 *   content/sources.en.json
 *
 * Every Chinese string is translated through one shared cache, so identical
 * sentences (boilerplate, group names, repeated caveats) come out identical
 * everywhere and are only paid for once.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import {
  collectTranslatable,
  localizeDocPaths,
  mapTranslatable,
  needsTranslation,
  translateTexts,
  TranslationCache,
} from "./i18n_core";
import { pickModel } from "./llm";
import {
  INSIGHTS_EN_JSON,
  INSIGHTS_JSON,
  METRICS_EN_JSON,
  METRICS_JSON,
  SOURCES_EN_JSON,
  SOURCES_JSON,
} from "./paths";

const args = process.argv.slice(2);
const has = (n: string) => args.includes(`--${n}`);
const opt = (n: string) => {
  const hit = args.find((a) => a.startsWith(`--${n}=`));
  return hit ? hit.slice(n.length + 3) : null;
};

/** A --limit run is a smoke test: translate, but never write a half-English file. */
/**
 * Chinese placeholder tokens inside metric-tag templates. The translation
 * prompt tells the model to copy anything inside backticks verbatim, which is
 * right for tag names but would leave `<数据集>` in an English sentence, so
 * they are mapped separately.
 */
const PLACEHOLDER = /<(数据集|类目|数据源|数字)>/g;
const PLACEHOLDER_EN: Record<string, string> = {
  "<数据集>": "<dataset>",
  "<类目>": "<category>",
  "<数据源>": "<source>",
  "<数字>": "<index>",
};

const DRY = has("dry-run") || Number(opt("limit")) > 0;
const FORCE = has("force");
const CONCURRENCY = Number(opt("concurrency")) || 5;
const MODEL = opt("model");
/** Debug aid: translate at most N strings this run. */
const LIMIT = Number(opt("limit")) || 0;
/** Max source characters per request; smaller batches survive slow gateways better. */
const BUDGET = Number(opt("budget")) || 1400;

function readJson(path: string): any {
  return JSON.parse(readFileSync(path, "utf8"));
}

/** Add provenance so a stale English file is detectable from the file itself. */
function stamp(obj: any, sourceUpdatedAt: unknown): any {
  return {
    ...obj,
    lang: "en",
    translated_from_updated_at: sourceUpdatedAt ?? null,
    translated_at: new Date().toISOString().replace(/\.\d{3}Z$/, "Z"),
    translation_note:
      "Generated by src/translate_content.ts. The Chinese files (metrics.json, insights.json, " +
      "sources.json) are canonical; edit those and re-run translate:content, never this file.",
  };
}

async function main(): Promise<void> {
  if (!existsSync(METRICS_JSON)) throw new Error(`missing ${METRICS_JSON}`);

  const metrics = readJson(METRICS_JSON);
  const insights = existsSync(INSIGHTS_JSON) ? readJson(INSIGHTS_JSON) : { items: [] };
  const sources = existsSync(SOURCES_JSON) ? readJson(SOURCES_JSON) : { items: [] };

  const all = [
    ...new Set([
      ...collectTranslatable(metrics),
      ...collectTranslatable(insights),
      ...collectTranslatable(sources),
    ]),
  ];
  console.log(
    `content: ${metrics.items?.length ?? 0} metric explainers, ${insights.items?.length ?? 0} insights, ` +
      `${sources.items?.length ?? 0} sources — ${all.length} distinct Chinese strings`,
  );

  const model = pickModel(MODEL);
  console.log(`model: ${model}  concurrency: ${CONCURRENCY}${FORCE ? "  (force)" : ""}`);

  const started = Date.now();
  await translateTexts(LIMIT ? all.slice(0, LIMIT) : all, {
    model,
    concurrency: CONCURRENCY,
    force: FORCE,
    budget: BUDGET,
  });

  /* The translator persisted its cache; read it back to build the lookup. */
  const cache = new TranslationCache(model);
  const lookup = (s: string) => {
    const base = needsTranslation(s) ? cache.get(s) ?? s : s;
    return localizeDocPaths(base).replace(PLACEHOLDER, (m) => PLACEHOLDER_EN[m] ?? m);
  };

  const metricsEn = stamp(mapTranslatable(metrics, lookup), metrics.updated_at);
  const insightsEn = stamp(mapTranslatable(insights, lookup), insights.updated_at);
  const sourcesEn = stamp(mapTranslatable(sources, lookup), sources.updated_at);

  for (const [label, doc] of [
    ["metrics", metricsEn],
    ["insights", insightsEn],
    ["sources", sourcesEn],
  ] as const) {
    const left = collectTranslatable(doc).length;
    console.log(`  ${label}.en: ${left ? `${left} strings left as-is` : "fully translated"}`);
  }

  if (DRY) {
    console.log("--dry-run: nothing written");
    return;
  }
  writeFileSync(METRICS_EN_JSON, JSON.stringify(metricsEn, null, 1) + "\n");
  writeFileSync(INSIGHTS_EN_JSON, JSON.stringify(insightsEn, null, 1) + "\n");
  writeFileSync(SOURCES_EN_JSON, JSON.stringify(sourcesEn, null, 1) + "\n");
  console.log(`wrote content/{metrics,insights,sources}.en.json in ${((Date.now() - started) / 1000).toFixed(1)}s`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
